name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
   
  workflow_dispatch:
 
 
jobs: 

  build:
  
    runs-on: ubuntu-latest
    
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: PerfAction for JMeter
      # You may pin to the exact commit or the version.
      # uses: QAInsights/PerfAction@f3959d0a69e7f23949add25d7e34a3ae167d6443
        uses: QAInsights/PerfAction@v3.1
        with:
          # jmeter test plan to execute
          test-plan-path: './SAMPLE_SCRIPT_3.jmx'
        env:
          CSV_PATH: './credentials.csv'
      # The env section sets an environment variable named CSV_PATH to './credentials.csv'
      # which is used by the JMeter test plan.
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
