name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: './SAMPLE_SCRIPT_3.jmx'
        env:
          CSV_PATH: './credentials.csv'

      - name: Generate HTML report
        uses: dherault/jmeter-results-report@v2
        with:
          source_files: result.jtl
        id: generate-report

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-report
          path: ${{ steps.generate-report.outputs.report_path }}
